### ISSUE TITLE
bug: parsing of switch

### ISSUE THREAD

**Issue by peter7891** [chikaku/gosyn#6]
The current tests for the switch aren't asserting the parsed AST is correct.
It is in fact, broken.

```go
switch x {
    case 5:
     print(5)
}
```

This generates a switch statement without a tag.

https://github.com/chikaku/gosyn/blob/main/src/parser.rs#L1923

I believe this should be moved inside the if statement above.
Like so

```rust
if self.skipped(Operator::SemiColon)? {
              init = tag;

              tag = self
                  .current_not(Operator::BraceLeft)
                  .then(|| self.parse_simple_stmt())
                  .map_or(Ok(None), |r| r.map(Some))?;
          }
```

Because currently, the tag gets parsed correctly before this and it gets overwritten with `None`

**Comment by chikaku** [comment]
Thanks! Now many test code can't make assertion effectively, I will rewrite them first to find more bugs.
